-- CreateTable
CREATE TABLE `DS_GN` (
    `Id1` CHAR(255) NOT NULL,
    `Id2` CHAR(255) NOT NULL,
    `Ten_Goi_Nho` TEXT NULL,
    `Email` CHAR(255) NOT NULL,
    `Phone` CHAR(255) NOT NULL,

    UNIQUE INDEX `DS_GN_Id1_key`(`Id1`),
    UNIQUE INDEX `DS_GN_Id2_key`(`Id2`),
    PRIMARY KEY (`Id1`, `Id2`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DS_GN` ADD CONSTRAINT `DS_GN_ibfk_1` FOREIGN KEY (`Id1`) REFERENCES `TK_TT`(`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `DS_GN` ADD CONSTRAINT `DS_GN_ibfk_2` FOREIGN KEY (`Id2`) REFERENCES `TK_TT`(`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
